version: '3.8'

services:
  app:
    image: app-crud:1.0.0
    build:
      context: ..
      dockerfile: dev/dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 