FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    gcc \
    build-essential

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"] 